### ISSUE TITLE
Mocked utils.js module is not picked up by Jest in CLI tests using child_process.exec

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/FlightTrackerCLI#17]
When testing a CLI application with Jest, the utils.js module is mocked to provide test-specific behavior. However, the mock is not picked up when the CLI script is executed using child_process.exec. Instead, the CLI uses the real implementation of utils.js, leading to unexpected behavior during tests.

This issue appears to occur because child_process.exec spawns a new Node.js process, which does not inherit Jest’s runtime or its mocked modules.

Steps to Reproduce:
	1.	Create a CLI script (flightTracker.js) that imports and uses utils.js.
	2.	Mock utils.js using jest.mock in the test file.
	3.	Write a test that runs the CLI script using child_process.exec.
	4.	Observe that the mocked implementation is not being used, and the real utils.js implementation is executed instead.
	
Expected Behavior:
The mocked utils.js module should be used when the CLI script is executed, allowing for isolated and controlled tests.

Actual Behavior:
The CLI script uses the real implementation of utils.js, causing tests to fail if the real implementation expects environment configurations (e.g., an API key).

Workarounds Attempted:
	1.	Verified that process.env.JEST_WORKER_ID is set, indicating Jest is running.
	2.	Mocked the utils.js module using jest.mock with a custom factory.
	3.	Passed an environment variable (TEST_MODE=true) to signal the script to use mocked behavior. However, this requires modifications to the CLI script.

**Comment by mdwiltfong** [comment]
To be more specific, this is how the mock was setup in `index.test.js`

```
jest.mock("../bin/utils/utils.js", () => {
  return {
    findIATACode: jest.fn(() => Promise.resolve("mocked IATA code")),
    findFlights: jest.fn(() => Promise.resolve("mocked flights")),
  };
});
```

Let's say you put a `console.log` in that callback, you'll see the log in your terminal, meaning the callback is being executed. Despite that, the terminal will log the following error: 

```
● CLI can run command findIATACode with null flag and test input › findIATACode should run with no flag and  "test" as input without errors

    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: [Error: Command failed: LOCAL_ENVIRONMENT=true node ./bin/flightTracker.js findIATACode test
    /Users/michael.wiltfong/FlightTrackerCLI/bin/utils/utils.js:14
          throw new Error(chalk.red("Error: API key is missing."));
                ^·
    Error: Error: API key is missing.
        at FlightTrackerCLI.findIATACode (/Users/michael.wiltfong/FlightTrackerCLI/bin/utils/utils.js:14:13)
        at Object.handler (/Users/michael.wiltfong/FlightTrackerCLI/bin/flightTracker.js:73:47)
        at /Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:8993
        at j (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:4956)
        at _.handleValidationAndGetResult (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:8962)
        at _.applyMiddlewareAndGetResult (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:9604)
        at _.runCommand (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:7231)
        at [runYargsParserAndExecuteCommands] (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:58539)
        at te.parse (/Users/michael.wiltfong/FlightTrackerCLI/node_modules/yargs/build/index.cjs:1:40478)
        at Object.<anonymous> (/Users/michael.wiltfong/FlightTrackerCLI/bin/flightTracker.js:103:4)·
    Node.js v20.9.0
    ]
    ```
    
    This means the original logic is getting picked up during execution and NOT the mock.

**Comment by mdwiltfong** [comment]
The problem here is that `npm test` starts it's own node process, in which `node blah blah` is another process. During this process jest loses context and that's why the mocks aren't getting picked up
